name: Prettier Check

on:
  - push
  - pull_request

jobs:
  test:
    name: Prettier Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0

      - name: Run Prettier Check
        run: |
          npm install prettier --prefix ./
          npm run style:check --prefix ./
